############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Team"
url = "team/"
weight = 2

[[main]]
name = "Blogs"
url = "blog/"
weight = 3

[[main]]
weight = 4
name = "Resources"
hasChildren = true

[[main]]
parent = "Pages"
name = "Resources"
url = "guides/"

[[main]]
parent = "Resources"
name = "ROMs and Recoveries"
url = "roms/"

# [[main]]
# parent = "Resources"
# name = "Categories"
# url = "categories/"

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 2
